### PR TITLE
Fixed #1. Updated ParseNumber to use invariant number format info.

### LINKED ISSUE #1: Parsing of literals should use invariant culture
First of all, thanks for taking the initiative to improve the original dynamic LINQ!
One of the issues I always had with the original library is that it used the default Parse methods without passing in InvariantCulture.

This means that numeric strings may actually parse or not depending on the user's environment. This becomes more confusing because for some cultures, decimal places may be confused with other lexer tokens and so on. Code should always be parsed with InvariantCulture anyway!

### PR DESCRIPTION
**Pull request by glopesdev**

### CODE REVIEW

**Comment by plainionist** [comment]
hi,

thx for providing this fix!

one question: for parsing "decimal" shouldnt NumberStyles be "float"?

**Comment by glopesdev** [comment]
Well, I followed what's in the reference source:
http://referencesource.microsoft.com/#mscorlib/system/decimal.cs

They call `NumberStyles.Number` by default. This is also mentioned in the method's documentation:
https://msdn.microsoft.com/en-us/library/9zbda557(v=vs.110).aspx

"Parameter s is interpreted using the `NumberStyles.Number` style."

By the way, I did the same w.r.t the other conventions (e.g. float, double). Basically followed what they do by default since they force you to specify `NumberStyles` if you want to override culture.

**Comment by plainionist** [comment]
hi,

thx for clarifying!
I merged your pull request.
thx for your contribution.

**Comment by plainionist** [comment]
fix included in nu-get package 1.2

**Pull request merged**
